workflows:
  ios_unsigned:
    name: iOS unsigned build
    environment:
      flutter: stable
      xcode: latest
      groups:
        - cobreCoin_env
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS (unsigned)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
