workflows:
  ios_unsigned:
    name: iOS unsigned build
    environment:
      flutter: stable
      xcode: latest
      groups:
        - cobreCoin_env
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Create .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_PUBLISHABLE=$SUPABASE_PUBLISHABLE" >> .env
      - name: Build iOS (unsigned)
        script: |
          flutter build ios --release --no-codesign
      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r build/ios/iphoneos/Runner-unsigned.ipa Payload
          rm -rf Payload
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner-unsigned.ipa
